baseurl = "https://r0B-O.github.io"
title = "Tech | Blog | Code"
theme = "ananke"
languageCode = "en-us"
paginate = 500 #frontpage pagination

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false

[params]
  header_image = "images/home-bg.jpg"
  title = "Enlightned"
  slogan = "$ grep -rni \"The how's and why's\" ."
  SEOTitle = "Rich Youngkin Blog"
  keyword = "Kiran, Chand, rob-o, r0B-O, Python, Cloud, Azure, AWS, Native, Docker, Kubernetes, Go, Golang, Microservice, Serverless"
 
  # Sidebar settings
  sidebar_about_description = "Cyclist, and, oh yeah, Loves Code | Coding | Coders"
  sidebar_avatar = "images/MeAtJackson.jpeg"
  about_me = true

  featured_tags = true 
  featured_condition_size = 2 # How many posts have to have a given tag to be featured (greater-than)

  image_404 = "images/404-bg.jpg"
  title_404 = "We couldn't find what you were looking for..."

  omit_categories = false

  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"

  [params.social]
  rss            = true
  email          = "root@rob-o.dev"
  linkedin       = "https://www.linkedin.com/in/kiranbchand"
  github         = "https://github.com/r0B-O"
  medium         = "https://medium.com/@RichYoungkin"
  stackoverflow  = "https://stackoverflow.com/users/2646870/rich"
  reddit         = "https://www.reddit.com/user/elevation5280"